"""create model registry tables

Revision ID: 076ed72e6295
Revises: 
Create Date: 2026-10-04 15:31:06.663164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076ed72e6295'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('problem_type', sa.String(), nullable=True),
    sa.Column('primary_metric', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_slug'), 'models', ['slug'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact_uri', sa.String(), nullable=True),
    sa.Column('git_commit', sa.String(), nullable=True),
    sa.Column('framework_version', sa.String(), nullable=True),
    sa.Column('python_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_version')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('evaluation_type', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_metrics')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_models_slug'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
