"""Add auth verification and token blacklisting

Revision ID: 0cdf15ba7272
Revises: 9219ec1c4490
Create Date: 2026-10-08 11:04:11.792843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdf15ba7272'
down_revision: Union[str, Sequence[str], None] = '9219ec1c4490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_tokens_token'), ['token'], unique=True)

    op.create_table('verification_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_tokens_token_hash'))

    op.drop_table('verification_tokens')
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_tokens_token'))

    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
