"""Add repository models

Revision ID: 2302003a5873
Revises: 798426701556
Create Date: 2026-10-06 00:09:20.247335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2302003a5873'
down_revision: Union[str, Sequence[str], None] = '798426701556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('current_commit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_table('repository_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('language_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_snapshots_commit_sha'), 'repository_snapshots', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_repository_snapshots_repository_id'), 'repository_snapshots', ['repository_id'], unique=False)
    op.create_table('repository_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_files_path'), 'repository_files', ['path'], unique=False)
    op.create_index(op.f('ix_repository_files_repository_snapshot_id'), 'repository_files', ['repository_snapshot_id'], unique=False)
    op.create_table('repository_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('target_reference', sa.String(), nullable=True),
    sa.Column('dependency_type', sa.String(), nullable=True),
    sa.Column('resolved_target_file_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ),
    sa.ForeignKeyConstraint(['resolved_target_file_id'], ['repository_files.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['repository_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_dependencies_repository_snapshot_id'), 'repository_dependencies', ['repository_snapshot_id'], unique=False)
    op.create_index(op.f('ix_repository_dependencies_source_file_id'), 'repository_dependencies', ['source_file_id'], unique=False)
    op.create_table('repository_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_file_id', sa.String(length=36), nullable=False),
    sa.Column('symbol_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('qualified_name', sa.String(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('parent_symbol', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_symbols_name'), 'repository_symbols', ['name'], unique=False)
    op.create_index(op.f('ix_repository_symbols_qualified_name'), 'repository_symbols', ['qualified_name'], unique=False)
    op.create_index(op.f('ix_repository_symbols_repository_file_id'), 'repository_symbols', ['repository_file_id'], unique=False)
    op.add_column('model_versions', sa.Column('repository_snapshot_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'repository_snapshot_id')
    op.drop_index(op.f('ix_repository_symbols_repository_file_id'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_qualified_name'), table_name='repository_symbols')
    op.drop_index(op.f('ix_repository_symbols_name'), table_name='repository_symbols')
    op.drop_table('repository_symbols')
    op.drop_index(op.f('ix_repository_dependencies_source_file_id'), table_name='repository_dependencies')
    op.drop_index(op.f('ix_repository_dependencies_repository_snapshot_id'), table_name='repository_dependencies')
    op.drop_table('repository_dependencies')
    op.drop_index(op.f('ix_repository_files_repository_snapshot_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_path'), table_name='repository_files')
    op.drop_table('repository_files')
    op.drop_index(op.f('ix_repository_snapshots_repository_id'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_repository_snapshots_commit_sha'), table_name='repository_snapshots')
    op.drop_table('repository_snapshots')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
