"""Add phase 9 models

Revision ID: 36702bf6ea3f
Revises: fb6a41b3b5d3
Create Date: 2026-10-06 17:21:22.819791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36702bf6ea3f'
down_revision: Union[str, Sequence[str], None] = 'fb6a41b3b5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('successful_patch_id', sa.String(), nullable=True),
    sa.Column('successful_validation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(), nullable=True),
    sa.Column('affected_metrics', sa.JSON(), nullable=True),
    sa.Column('affected_features', sa.JSON(), nullable=True),
    sa.Column('affected_segments', sa.JSON(), nullable=True),
    sa.Column('signal_families', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('resolution_status', sa.String(), nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['successful_patch_id'], ['patch_proposals.id'], ),
    sa.ForeignKeyConstraint(['successful_validation_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('regression_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_incident_id', sa.String(), nullable=False),
    sa.Column('incident_memory_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_signature', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('failure_metrics', sa.JSON(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('affected_features', sa.JSON(), nullable=True),
    sa.Column('affected_segments', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_memory_id'], ['incident_memories.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['source_incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regression_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('regression_case_id', sa.String(), nullable=False),
    sa.Column('validation_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regression_case_id'], ['regression_cases.id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regression_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('regression_run_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('segment_name', sa.String(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['regression_run_id'], ['regression_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regression_results')
    op.drop_table('regression_runs')
    op.drop_table('regression_cases')
    op.drop_table('incident_memories')
    # ### end Alembic commands ###
