"""add_resolution_memory

Revision ID: 5a96859dc921
Revises: a721335ae141
Create Date: 2026-10-07 09:49:46.630900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a96859dc921'
down_revision: Union[str, Sequence[str], None] = 'a721335ae141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_memory_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('patch_id', sa.String(), nullable=True),
    sa.Column('validation_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('affected_files', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('ml_recovery_score', sa.Float(), nullable=True),
    sa.Column('regression_status', sa.String(), nullable=True),
    sa.Column('deployment_status', sa.String(), nullable=True),
    sa.Column('post_deployment_status', sa.String(), nullable=True),
    sa.Column('recurrence_count', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['incident_memory_id'], ['incident_memories.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patch_proposals.id'], ),
    sa.ForeignKeyConstraint(['validation_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_memory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution_memories')
    # ### end Alembic commands ###
