"""Verify schema sync

Revision ID: 9219ec1c4490
Revises: 9378625ef7c2
Create Date: 2026-10-08 10:19:41.583063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9219ec1c4490'
down_revision: Union[str, Sequence[str], None] = '9378625ef7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))

    with op.batch_alter_table('repository_dependencies', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_repo_dependencies_resolved_symbol', 'repository_symbols', ['resolved_target_symbol_id'], ['id'])

    with op.batch_alter_table('workflow_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approval_role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approval_comment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_comment', sa.String(), nullable=True))
        batch_op.drop_column('responded_at')
        batch_op.drop_column('reviewer')
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('reviewer', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('responded_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('rejection_comment')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('approval_comment')
        batch_op.drop_column('approval_role')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')

    with op.batch_alter_table('repository_dependencies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
