"""add patch models

Revision ID: 95aad60df2a1
Revises: 2302003a5873
Create Date: 2026-10-06 01:34:09.002832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95aad60df2a1'
down_revision: Union[str, Sequence[str], None] = '2302003a5873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('repository_snapshot_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_patch_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('risk_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_patch_id'], ['patch_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_proposals_id'), 'patch_proposals', ['id'], unique=False)
    op.create_table('patch_file_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patch_proposal_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('target_symbol', sa.String(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('original_hash', sa.String(), nullable=True),
    sa.Column('proposed_hash', sa.String(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_proposal_id'], ['patch_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_file_changes_id'), 'patch_file_changes', ['id'], unique=False)
    op.create_table('patch_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patch_proposal_id', sa.String(), nullable=False),
    sa.Column('reviewer_type', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patch_proposal_id'], ['patch_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_reviews_id'), 'patch_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patch_reviews_id'), table_name='patch_reviews')
    op.drop_table('patch_reviews')
    op.drop_index(op.f('ix_patch_file_changes_id'), table_name='patch_file_changes')
    op.drop_table('patch_file_changes')
    op.drop_index(op.f('ix_patch_proposals_id'), table_name='patch_proposals')
    op.drop_table('patch_proposals')
    # ### end Alembic commands ###
