"""Add reliability timeline models

Revision ID: a721335ae141
Revises: d0a2d6d96548
Create Date: 2026-10-06 19:51:09.890677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a721335ae141'
down_revision: Union[str, Sequence[str], None] = 'd0a2d6d96548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reliability_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reliability_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reliability_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reliability_events_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reliability_events_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reliability_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('reliability_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_event_id', sa.String(), nullable=False),
    sa.Column('to_event_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_event_id'], ['reliability_events.id'], ),
    sa.ForeignKeyConstraint(['to_event_id'], ['reliability_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reliability_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reliability_edges_from_event_id'), ['from_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reliability_edges_to_event_id'), ['to_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reliability_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reliability_edges_to_event_id'))
        batch_op.drop_index(batch_op.f('ix_reliability_edges_from_event_id'))

    op.drop_table('reliability_edges')
    with op.batch_alter_table('reliability_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reliability_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_reliability_events_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_reliability_events_model_id'))
        batch_op.drop_index(batch_op.f('ix_reliability_events_event_type'))

    op.drop_table('reliability_events')
    # ### end Alembic commands ###
