"""add monitoring schema

Revision ID: afecbcb72c15
Revises: 076ed72e6295
Create Date: 2026-10-04 16:50:22.125875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afecbcb72c15'
down_revision: Union[str, Sequence[str], None] = '076ed72e6295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('baseline_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('health_summary', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monitoring_run_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_monitoring_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monitoring_run_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('drift_method', sa.String(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('baseline_summary', sa.JSON(), nullable=True),
    sa.Column('current_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monitoring_run_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('segment_name', sa.String(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_monitoring_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monitoring_run_id', sa.String(), nullable=False),
    sa.Column('prediction_metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_analysis_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monitoring_run_id', sa.String(), nullable=False),
    sa.Column('segment_name', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Float(), nullable=False),
    sa.Column('primary_metric', sa.String(), nullable=False),
    sa.Column('baseline_metric_value', sa.Float(), nullable=True),
    sa.Column('current_metric_value', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_analysis_results')
    op.drop_table('prediction_monitoring_results')
    op.drop_table('metric_results')
    op.drop_table('feature_monitoring_results')
    op.drop_table('data_quality_results')
    op.drop_table('monitoring_runs')
    # ### end Alembic commands ###
