"""Add policy fields to deployment

Revision ID: d8ce2a5ab0e4
Revises: 53cdffedb197
Create Date: 2026-10-06 21:49:15.874045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ce2a5ab0e4'
down_revision: Union[str, Sequence[str], None] = '53cdffedb197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_result', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('policy_evaluation_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_deploy_policy_eval', 'policy_evaluations', ['policy_evaluation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deploy_policy_eval', type_='foreignkey')
        batch_op.drop_column('policy_evaluation_id')
        batch_op.drop_column('policy_result')
    # ### end Alembic commands ###
