"""add_phase_13_change_risk

Revision ID: fa4e1d1b8683
Revises: fe6dde7f4d94
Create Date: 2026-10-06 18:56:52.414587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4e1d1b8683'
down_revision: Union[str, Sequence[str], None] = 'fe6dde7f4d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_risk_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patch_proposal_id', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('blast_radius', sa.JSON(), nullable=False),
    sa.Column('recommended_regressions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['patch_proposal_id'], ['patch_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_risk_assessments_id'), 'change_risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_change_risk_assessments_patch_proposal_id'), 'change_risk_assessments', ['patch_proposal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_risk_assessments_patch_proposal_id'), table_name='change_risk_assessments')
    op.drop_index(op.f('ix_change_risk_assessments_id'), table_name='change_risk_assessments')
    op.drop_table('change_risk_assessments')
    # ### end Alembic commands ###
