"""add_validation_models

Revision ID: fb6a41b3b5d3
Revises: 95aad60df2a1
Create Date: 2026-10-06 02:28:06.720979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6a41b3b5d3'
down_revision: Union[str, Sequence[str], None] = '95aad60df2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patch_proposal_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('repository_snapshot_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patch_proposal_id'], ['patch_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_snapshot_id'], ['repository_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_id'), 'validation_runs', ['id'], unique=False)
    op.create_table('validation_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('validation_run_id', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_artifacts_id'), 'validation_artifacts', ['id'], unique=False)
    op.create_table('validation_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('validation_run_id', sa.String(), nullable=False),
    sa.Column('check_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_checks_id'), 'validation_checks', ['id'], unique=False)
    op.create_table('validation_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('validation_run_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('patched_value', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('segment_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_metrics_id'), 'validation_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_metrics_id'), table_name='validation_metrics')
    op.drop_table('validation_metrics')
    op.drop_index(op.f('ix_validation_checks_id'), table_name='validation_checks')
    op.drop_table('validation_checks')
    op.drop_index(op.f('ix_validation_artifacts_id'), table_name='validation_artifacts')
    op.drop_table('validation_artifacts')
    op.drop_index(op.f('ix_validation_runs_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    # ### end Alembic commands ###
