"""add_phase_11_deployment_verification

Revision ID: fe6dde7f4d94
Revises: 35b690fc2c6a
Create Date: 2026-10-06 18:23:33.384256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6dde7f4d94'
down_revision: Union[str, Sequence[str], None] = '35b690fc2c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('baseline_reference', sa.JSON(), nullable=True),
    sa.Column('post_deployment_observation', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_verifications_id'), 'deployment_verifications', ['id'], unique=False)
    op.add_column('deployments', sa.Column('deployed_at', sa.DateTime(), nullable=True))
    op.add_column('deployments', sa.Column('environment', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('deployment_source', sa.String(), nullable=True))
    op.add_column('deployments', sa.Column('deployed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'deployed_by')
    op.drop_column('deployments', 'deployment_source')
    op.drop_column('deployments', 'environment')
    op.drop_column('deployments', 'deployed_at')
    op.drop_index(op.f('ix_deployment_verifications_id'), table_name='deployment_verifications')
    op.drop_table('deployment_verifications')
    # ### end Alembic commands ###
